[tool.black]
line-length = 88

[tool.pylint.messages_control]
disable = [
    "duplicate-code",
    "line-too-long",
    "too-few-public-methods",
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-return-statements",
    "too-many-statements",
    "no-member"
]
